### ISSUE TITLE
启动之后会自动终止python程序...

### ISSUE THREAD

**Issue by HeiLAAS** [kitUIN/ioobot#1]
为什么会自动断开链接啊...

**Comment by kitUIN** [comment]
可以详细点吗
是链接OPQ机器人出现问题还是python进程崩溃
最好能贴上报错消息方便我维护

**Comment by HeiLAAS** [comment]
python进程崩溃
但是我发现把python-iotbot模块换为2.7.0就不会崩溃了。估计是模块的问题

**Comment by kitUIN** [comment]
可是我没有用到python-iotbot库哇。

**Comment by kitUIN** [comment]
我这里挂了很久了都没遇上你所说的崩溃
[botoy的崩溃issues看到你了](https://github.com/xiyaowong/botoy/issues/12)

**Comment by HeiLAAS** [comment]
Logs也没出啥问题，就是启动，然后获取群聊信息。websocket断开，websocket重新连接。重复几次就python异常退出了。可以是我环境的问题
