### ISSUE TITLE
这个怎么办啊

### ISSUE THREAD

**Issue by 159764** [kitUIN/ioobot#2]
❌ 2021-02-24 12:53:39 ERROR	name '_USERNAME' is not defined
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2aaf33ae50>
    └ <Thread(ThreadPoolExecutor-0_5, started daemon 139820647053056)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2aaf33ab80>
    └ <Thread(ThreadPoolExecutor-0_5, started daemon 139820647053056)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_5, started daemon 139820647053056)>
    │    │        │    └ (<weakref at 0x7f2aa55bb040; to 'WorkerPool' at 0x7f2aaea7f3a0>, <_queue.SimpleQueue object at 0x7f2aac0f9950>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_5, started daemon 139820647053056)>
    │    └ <function _worker at 0x7f2aadea8ee0>
    └ <Thread(ThreadPoolExecutor-0_5, started daemon 139820647053056)>
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f2aadead040>
    └ <concurrent.futures.thread._WorkItem object at 0x7f2aade31910>
> File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f2aade31910>
             │    │   │    └ [<botoy.model.FriendMsg object at 0x7f2aac089f10>]
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f2aade31910>
             │    └ <function queued_up.<locals>.inner at 0x7f2aac07e310>
             └ <concurrent.futures.thread._WorkItem object at 0x7f2aade31910>
  File "/home/suda/.local/lib/python3.8/site-packages/botoy/decorators/_queued_up.py", line 20, in inner
    ret = func(ctx)
          │    └ <botoy.model.FriendMsg object at 0x7f2aac089f10>
          └ <function ignore_botself.<locals>.inner at 0x7f2aac07e040>
  File "/home/suda/.local/lib/python3.8/site-packages/botoy/decorators/_ignore_botself.py", line 16, in inner
    return func(ctx)
           │    └ <botoy.model.FriendMsg object at 0x7f2aac089f10>
           └ <function receive_friend_msg at 0x7f2aade35c10>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 634, in receive_friend_msg
    Setu(ctx, friend_info[2], friend_info[1], friend_info[3]).main()
    │    │    │               │               └ <re.Match object; span=(0, 4), match='来张色图'>
    │    │    │               └ <re.Match object; span=(0, 4), match='来张色图'>
    │    │    └ <re.Match object; span=(0, 4), match='来张色图'>
    │    └ <botoy.model.FriendMsg object at 0x7f2aac089f10>
 └ <class 'plugins.bot_setu.Setu'>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 537, in main
    self.friend()
    │    └ <function Setu.friend at 0x7f2aac0e9ca0>
    └ <plugins.bot_setu.Setu object at 0x7f2aac07f700>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 531, in friend
    self.processing_and_inspect()
    │    └ <function Setu.processing_and_inspect at 0x7f2aac0e9b80>
    └ <plugins.bot_setu.Setu object at 0x7f2aac07f700>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 480, in processing_and_inspect
    self.send()
    │    └ <function Setu._freq.<locals>.wrapper at 0x7f2aac0e9e50>
    └ <plugins.bot_setu.Setu object at 0x7f2aac07f700>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 437, in wrapper
    func(self, *args, **kwargs)
    │    │      │       └ {}
    │    │      └ ()
    │    └ <plugins.bot_setu.Setu object at 0x7f2aac07f700>
    └ <function Setu.send at 0x7f2aac0e9dc0>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 545, in send
    self.api_2()
    │    └ <function Setu.api_2 at 0x7f2aac0e9a60>
    └ <plugins.bot_setu.Setu object at 0x7f2aac07f700>

  File "/home/suda/桌面/ioobot/plugins/bot_setu.py", line 389, in api_2
    api2 = pixivsetu(_USERNAME, _PASSWORD, self.ctx)
           │                               │    └ <botoy.model.FriendMsg object at 0x7f2aac089f10>
           │                               └ <plugins.bot_setu.Setu object at 0x7f2aac07f700>
           └ <class 'plugins.bot_setu.pixivsetu'>

NameError: name '_USERNAME' is not defined

**Comment by kitUIN** [comment]
你开启了pixiv功能却没有输入pixiv的账号和密码

**Comment by kitUIN** [comment]
新版本已修复
可以重新git项目更新

**Comment by 159764** [comment]
ok

**Comment by 159764** [comment]
2021-02-25 16:26:24 ERROR	返回为null
ℹ️ 2021-02-25 16:26:24 INFO	从yubanのapi获取到1张setu  实际发送1张
不好意识，这个是啥情况emmm

**Comment by kitUIN** [comment]
`ERROR 返回为null`
该错误大概率是因为QQ被风控
可以挂机几天看看是否恢复

**Comment by 159764** [comment]
ok
