### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by Fhm-newbie** [kitUIN/ioobot#3]
大佬您好，我在装好了bot启动后显示有更新版本建议更新，我根据其他bot上的经验git pull了一下但是没有用，能请教一下怎么更新吗？

**Comment by Fhm-newbie** [comment]
而且我用setu命令显示了api0 boom是为啥啊。。。

**Comment by kitUIN** [comment]
我这个都多久没更新了啊。。。
建议移步到→https://github.com/opq-osc/OPQ-SetuBot

**Comment by Fhm-newbie** [comment]
阿哲。。。我本来用的是那个setubot，但是我看这边有ascii搜索就又装了这个。。。然后不能用又想启动setubot，结果发现那边运行不了了。。。显示没有jconfig。。。

**Comment by kitUIN** [comment]
那你得询问那边的开发者了。
我这个项目是不更新了，他家setubot基本上覆盖我的功能了。

**Comment by Fhm-newbie** [comment]
好的

**Comment by kitUIN** [comment]
毕竟我这个bot诞生原因就是因为他太久不更新。
